export const SET_IS_CART_OPEN = 'SET_IS_CART_OPEN';
export const SET_CART_ITEMS = 'SET_CART_ITEMS';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';

export const REMOVE_ALERT = 'REMOVE_ALERT';
