export const GET_ALL_PET_REVIEWS_STARTS = 'GET_ALL_PET_REVIEWS_STARTS';
export const GET_ALL_PET_REVIEWS_SUCCESS = 'GET_ALL_PET_REVIEWS_SUCCESS';
export const GET_ALL_PET_REVIEWS_FAILED = 'GET_ALL_PET_REVIEWS_FAILED';

export const REMOVE_ALERT = 'REMOVE_ALERT';
