export const GET_ALL_PETS_STARTS = 'GET_ALL_PETS_STARTS';
export const GET_ALL_PETS_SUCCESS = 'GET_ALL_PETS_SUCCESS';
export const GET_ALL_PETS_FAIL = 'GET_ALL_PETS_FAIL';
export const GET_PET_STARTS = 'GET_ALL_PETS_STARTS';
export const GET_PET_SUCCESS = 'GET_ALL_PETS_SUCCESS';
export const GET_PET_FAIL = 'GET_ALL_PETS_FAIL';
