export const GET_ALL_PETS_STARTS = 'GET_ALL_PETS_STARTS';
export const GET_ALL_PETS_SUCCESS = 'GET_ALL_PETS_SUCCESS';
export const GET_ALL_PETS_FAILED = 'GET_ALL_PETS_FAILED';

export const REMOVE_ALERT = 'REMOVE_ALERT';
