export const GET_ALL_PETS_STARTS = 'GET_ALL_PETS_STARTS';
export const GET_ALL_PETS_SUCCESS = 'GET_ALL_PETS_SUCCESS';
export const GET_ALL_PETS_FAILED = 'GET_ALL_PETS_FAILED';

export const GET_PET_REVIEWS_STARTS = 'GET_PET_REVIEWS_STARTS';
export const GET_PET_REVIEWS_SUCCESS = 'GET_PET_REVIEWS_SUCCESS';
export const GET_PET_REVIEWS_FAILED = 'GET_PET_REVIEWS_FAILED';

export const REMOVE_ALERT = 'REMOVE_ALERT';
