export const GET_ALL_REVIEWS_STARTS = 'GET_ALL_REVIEWS_STARTS';
export const GET_ALL_REVIEWS_SUCCESS = 'GET_ALL_REVIEWS_SUCCESS';
export const GET_ALL_REVIEWS_FAIL = 'GET_ALL_REVIEWS_FAIL';
export const GET_A_REVIEW_STARTS = 'GET_A_REVIEW_STARTS';
export const GET_A_REVIEW_SUCCESS = 'GET_A_REVIEW_SUCCESS';
export const GET_A_REVIEW_FAIL = 'GET_A_REVIEW__FAIL';
