export const ACTIVE_USER_STARTS = 'ACTIVE_USER_STARTS';
export const ACTIVE_USER_SUCCESS = 'ACTIVE_USER_SUCCESS';
export const ACTIVE_USER_FAILED = 'ACTIVE_USER_FAILED';

export const LOGIN_USER_STARTS = 'LOGIN_USER_STARTS';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const LOGOUT_USER_START = 'LOGOUT_USER_START';
export const LOGOUT_USER_FAILED = 'LOGOUT_USER_FAILED';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const REGISTER_USER_STARTS = 'REGISTER_USER_STARTS';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const UPDATE_USER_STARTS = 'UPDATE_USER_STARTS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';

export const REMOVE_ALERT = 'REMOVE_ALERT';
